
platform :ios, '9.0'

use_frameworks!

target 'Closurable_Example' do
  pod 'Closurable', :path => '../'
  pod 'SwiftLint'

  target 'Closurable_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
